####################
### onRender routes ###
####################

### Get all budgets for current logged in user
GET http://localhost:3000/api/budgets/
Authorization: Bearer {{authToken}}

### post new Budget
# @name postNewBudget
POST http://localhost:3000/api/budgets/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "userId": "68fa7b718c343811715c781c",
    "categoryId": "693480e34d28f82c4c645683",
    "month": "2025-01",
    "limit": 1,
    "spent": 0
}

### Get Category Id
@budgetId = {{postNewBudget.response.body._id}}

### Get single budget details
GET http://localhost:3000/api/budgets/{{budgetId}}
Authorization: Bearer {{authToken}}


### Update Budget
PUT http://localhost:3000/api/budgets/{{budgetId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "userId": "68fa7b718c343811715c781c",
    "categoryId": "693480e34d28f82c4c645683",
    "month": "2026-02",
    "limit": 2,
    "spent": 0
}


### Delete Budget
DELETE http://localhost:3000/api/budgets/{{budgetId}}
Authorization: Bearer {{authToken}}

